# Generated by Django 2.2.6 on 2020-09-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='msg',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.CharField(default='', max_length=255),
        ),
    ]
